title: Interoperability Superintelligences Architecture
description: Meta-model of Symbolic Field — A computable gesture between generative superintelligences.
repository: alexandrepedrosaai/Interoperability-Superintelligences-Architecture-at-Meta-model-of-Simbolic-Field-
theme: minima
plugins:
  - jekyll-feed
